package org.example.java.entity;

import org.example.java.entity.guest.Guest;
import org.example.java.entity.admin.Admin;
import org.example.java.entity.user.User;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("User Entity Tests")
class UserTest {

    @Test
    @DisplayName("Should create guest with auto-generated UUID")
    void testGuestCreationWithAutoGeneratedId() {
        Guest guest1 = new Guest("John", 25);
        Guest guest2 = new Guest("Jane", 30);

        assertNotNull(guest1.getId());
        assertNotNull(guest2.getId());
        assertNotEquals(guest1.getId(), guest2.getId(), "Each guest should have unique ID");
    }

    @Test
    @DisplayName("Should create guest with specific UUID")
    void testGuestCreationWithSpecificId() {
        UUID id = UUID.randomUUID();
        Guest guest = new Guest(id, "Alice", 28);

        assertEquals(id, guest.getId());
        assertEquals("Alice", guest.getName());
        assertEquals(28, guest.getAge());
    }

    @Test
    @DisplayName("Should create admin with auto-generated UUID")
    void testAdminCreationWithAutoGeneratedId() {
        Admin admin1 = new Admin("Manager1", 40);
        Admin admin2 = new Admin("Manager2", 45);

        assertNotNull(admin1.getId());
        assertNotNull(admin2.getId());
        assertNotEquals(admin1.getId(), admin2.getId(), "Each admin should have unique ID");
    }

    @Test
    @DisplayName("Should create admin with specific UUID")
    void testAdminCreationWithSpecificId() {
        UUID id = UUID.randomUUID();
        Admin admin = new Admin(id, "Admin", 50);

        assertEquals(id, admin.getId());
        assertEquals("Admin", admin.getName());
        assertEquals(50, admin.getAge());
    }

    @Test
    @DisplayName("Should get user properties correctly")
    void testGetUserProperties() {
        Guest guest = new Guest("Bob", 35);

        assertEquals("Bob", guest.getName());
        assertEquals(35, guest.getAge());
        assertNotNull(guest.getId());
    }

    @Test
    @DisplayName("Should have equal users with same name and age")
    void testUserEquality() {
        Guest guest1 = new Guest("Tom", 40);
        Guest guest2 = new Guest("Tom", 40);

        assertEquals(guest1, guest2, "Users with same name and age should be equal");
    }

    @Test
    @DisplayName("Should have unequal users with different name")
    void testUserInequalityDifferentName() {
        Guest guest1 = new Guest("Tom", 40);
        Guest guest2 = new Guest("Jerry", 40);

        assertNotEquals(guest1, guest2);
    }

    @Test
    @DisplayName("Should have unequal users with different age")
    void testUserInequalityDifferentAge() {
        Guest guest1 = new Guest("Tom", 40);
        Guest guest2 = new Guest("Tom", 30);

        assertNotEquals(guest1, guest2);
    }

    @Test
    @DisplayName("Should have same hash code for equal users")
    void testUserHashCode() {
        Guest guest1 = new Guest("Tom", 40);
        Guest guest2 = new Guest("Tom", 40);

        assertEquals(guest1.hashCode(), guest2.hashCode(), "Equal users should have same hash code");
    }

    @Test
    @DisplayName("Should generate correct toString representation")
    void testUserToString() {
        Guest guest = new Guest("Alice", 25);
        String toString = guest.toString();

        assertTrue(toString.contains("Alice"), "toString should contain name");
        assertTrue(toString.contains("25"), "toString should contain age");
    }

    @Test
    @DisplayName("Should return keywords for searchability")
    void testUserKeywords() {
        Guest guest = new Guest("SearchMe", 35);
        var keywords = guest.getKeyWord();

        assertNotNull(keywords);
        assertTrue(keywords.size() > 0, "Should have keywords");
        assertTrue(keywords.stream().anyMatch(p -> p.getKey().equals("Name")), "Should have Name keyword");
        assertTrue(keywords.stream().anyMatch(p -> p.getValue().equals("SearchMe")), "Should contain name value");
    }

    @ParameterizedTest
    @ValueSource(ints = {1, 18, 65, 100})
    @DisplayName("Should accept various valid ages")
    void testValidAges(int age) {
        Guest guest = new Guest("TestUser", age);
        assertEquals(age, guest.getAge());
    }

    @Test
    @DisplayName("User should not be equal to null")
    void testUserNotEqualToNull() {
        Guest guest = new Guest("Alice", 25);
        assertNotEquals(null, guest);
    }

    @Test
    @DisplayName("User should not be equal to different type object")
    void testUserNotEqualToDifferentType() {
        Guest guest = new Guest("Alice", 25);
        assertNotEquals("Alice", guest);
    }
}
